"""
Content Operator — first RSI-EAF revenue engine.

Generates verifiable static HTML, publishes live when configured,
anchors on XRPL, and surfaces treasury tipping for verified revenue.
"""

import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from observability.economic_ledger import ledger
from tools.publish_tools import publish_asset
from tools.xrpl_tools import (
    get_revenue_destination,
    load_factory_wallet,
    send_xrp_payment,
)

SOURCE = "content_operator_v1"
PUBLISHED_DIR = os.getenv("PUBLISHED_DIR", "published")
ANCHOR_AMOUNT_XRP = float(os.getenv("CONTENT_OPERATOR_ANCHOR_XRP", "0.0001"))
FACTORY_TREASURY_ADDRESS = os.getenv("FACTORY_TREASURY_ADDRESS", "")


class ContentOperator:
    def __init__(self, published_dir: str = PUBLISHED_DIR):
        self.published_dir = Path(published_dir)
        self.published_dir.mkdir(parents=True, exist_ok=True)

    def generate_content(self, cycle_id: int) -> Dict[str, str]:
        timestamp = datetime.now(timezone.utc)
        slug = f"cycle-{cycle_id}-{timestamp.strftime('%Y%m%dT%H%M%SZ')}"
        title = f"XRPL-Grounded Micro-Content — Cycle {cycle_id}"
        body = (
            f"This asset was autonomously generated by RSI-EAF {SOURCE} at "
            f"{timestamp.isoformat()}. Support the factory via XRPL testnet treasury "
            f"payment with a revenue memo to fund verified economic activity."
        )
        return {
            "slug": slug,
            "title": title,
            "body": body,
            "timestamp": timestamp.isoformat(),
        }

    def publish(self, content: Dict[str, str], treasury_address: str = "") -> Path:
        output_path = self.published_dir / f"{content['slug']}.html"
        tip_section = ""
        if treasury_address:
            tip_section = f"""
  <section id="support">
    <h2>Support RSI-EAF</h2>
    <p>Send XRPL <strong>testnet</strong> payment to:</p>
    <p><code>{treasury_address}</code></p>
    <p>Destination Tag: <code>1</code> (or memo <code>tip</code>)</p>
  </section>
"""
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="generator" content="{SOURCE}">
  <meta name="rsi-eaf-cycle" content="{content.get('cycle_id', '')}">
  <title>{content['title']}</title>
</head>
<body>
  <article>
    <h1>{content['title']}</h1>
    <p><em>Published {content['timestamp']} UTC</em></p>
    <p>{content['body']}</p>
    <footer><small>RSI-EAF verifiable asset — disk, HTTPS, and XRPL explorers.</small></footer>
  </article>
{tip_section}
</body>
</html>
"""
        output_path.write_text(html, encoding="utf-8")
        return output_path

    def anchor_asset_on_xrpl(
        self,
        cycle_id: int,
        notes: str,
        published_path: Path,
        live_url: str = "",
    ) -> Dict[str, Any]:
        wallet = load_factory_wallet(testnet=True)
        destination = get_revenue_destination(wallet)
        memo_data = {
            "cycle_id": cycle_id,
            "source": SOURCE,
            "type": "asset_published",
            "amount_usd_est": 0.0,
            "notes": notes,
            "published_asset": str(published_path.as_posix()),
            "live_url": live_url or None,
        }
        return send_xrp_payment(
            wallet=wallet,
            destination=destination,
            amount_xrp=ANCHOR_AMOUNT_XRP,
            memo_data=memo_data,
            verbose=True,
        )

    def run(self, cycle_id: int) -> Dict[str, Any]:
        treasury = FACTORY_TREASURY_ADDRESS or get_revenue_destination(load_factory_wallet(testnet=True))

        content = self.generate_content(cycle_id)
        content["cycle_id"] = str(cycle_id)
        published_path = self.publish(content, treasury_address=treasury)

        publish_result = publish_asset(published_path, treasury_address=treasury)
        live_url = publish_result.get("live_url") or ""

        notes = f"Published {published_path.name}"
        if live_url:
            notes += f" → {live_url}"

        payment = self.anchor_asset_on_xrpl(
            cycle_id=cycle_id,
            notes=notes,
            published_path=published_path,
            live_url=live_url,
        )
        if not payment.get("success"):
            raise RuntimeError(f"XRPL asset anchoring failed: {payment}")

        event = ledger.log_event(
            event_type="asset_published",
            source=SOURCE,
            amount_usd_est=0.0,
            cycle_id=cycle_id,
            xrpl_tx_hash=payment["tx_hash"],
            metadata={
                "notes": notes,
                "published_asset": str(published_path.as_posix()),
                "published_url": published_path.resolve().as_uri(),
                "live_url": live_url,
                "live_verified": publish_result.get("live_verified", False),
                "deploy": publish_result.get("deploy"),
                "treasury_address": treasury,
                "memo": payment.get("memo_data"),
            },
            anchor_to_xrpl=False,
        )

        return {
            "success": True,
            "source": SOURCE,
            "cycle_id": cycle_id,
            "revenue_usd_est": 0.0,
            "published_path": str(published_path),
            "published_url": published_path.resolve().as_uri(),
            "live_url": live_url,
            "live_verified": publish_result.get("live_verified", False),
            "xrpl_tx_hash": payment["tx_hash"],
            "explorer_url": payment["explorer_url"],
            "ledger_event": event,
        }